name: Deploy to S3

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Sync to S3 (immutable cache for assets)
        run: |
          aws s3 sync . s3://pwa-imageeffects \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude ".DS_Store" \
            --cache-control "max-age=31536000, public, immutable"

      - name: Set cache/content-type for HTML, SW, Manifest
        run: |
          aws s3 cp index.html s3://pwa-imageeffects/index.html \
            --cache-control "no-cache, max-age=0" \
            --content-type "text/html"
          aws s3 cp sw.js s3://pwa-imageeffects/sw.js \
            --cache-control "no-cache, max-age=0" \
            --content-type "application/javascript"
          aws s3 cp manifest.json s3://pwa-imageeffects/manifest.json \
            --cache-control "no-cache, max-age=0" \
            --content-type "application/manifest+json"

